# Generated by Django 2.2.5 on 2020-02-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('industry', models.CharField(max_length=250)),
                ('poc', models.CharField(max_length=250)),
                ('logo', models.FileField(default='https://image.shutterstock.com/image-vector/picture-vector-icon-no-image-260nw-1350441335.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Company')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Hostel')),
            ],
        ),
    ]
