# Generated by Django 2.2.5 on 2020-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200202_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.FileField(default='https://image.shutterstock.com/image-vector/picture-vector-icon-no-image-260nw-1350441335.jpg', upload_to=''),
        ),
    ]
