# Generated by Django 2.2.5 on 2020-02-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200202_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
