# Generated by Django 2.2.2 on 2020-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image',
        ),
    ]
