# Generated by Django 2.2.5 on 2020-02-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200209_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
