# Generated by Django 2.2.5 on 2020-02-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_hostel_image'),
        ('room', '0009_auto_20200209_1927'),
    ]

    operations = [
    ]
