# Generated by Django 2.2.4 on 2020-02-16 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20200215_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='room number must be of form: A-9', regex='^([A-Z])-([0-9])+$')])),
                ('hostel', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=250)),
            ],
        ),
    ]
