# Generated by Django 2.2.5 on 2020-02-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20200215_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Hostels', to='room.Hostel'),
        ),
    ]
