# Generated by Django 2.2.5 on 2020-02-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_data'),
        ('room', '0013_auto_20200216_0917'),
    ]

    operations = [
    ]
