# Generated by Django 2.2.5 on 2020-02-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_auto_20200216_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data Set'},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'verbose_name': 'Hostels'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Rooms'},
        ),
    ]
