# Generated by Django 2.2.5 on 2020-02-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_auto_20200216_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companie'},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'verbose_name': 'Hostel'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room'},
        ),
    ]
