# Generated by Django 2.2.5 on 2020-02-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_auto_20200216_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.Company'),
        ),
    ]
